version: '3.7'
services:
  api:
    container_name: sloth_api
    restart: always
    build: .
    ports:
      - "9070:8080"
    environment:
      TZ: ${CONTAINER_TIMEZONE}
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    container_name: sloth_mysql
    restart: always
    build: database
    volumes:
      - ~/.volumes/sloth/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DATABASE: ${DB_SCHEMA}
      TZ: ${CONTAINER_TIMEZONE}
    env_file:
      - .env
volumes:
  mysql-data:
  apk-cache:
